### ISSUE TITLE
Production Mode Compilation overrides ComboBox Styles

### ISSUE THREAD

**Issue by Juchar** [gatanaso/multiselect-combo-box#10]
I made the following observation:

If you compile your application in production mode, then the styles provided in [multiselect-combo-box-styles.html](https://github.com/gatanaso/multiselect-combo-box/blob/master/theme/lumo/multiselect-combo-box-styles.html), `<dom-module id="lumo-combo-box-item-theme" theme-for="vaadin-combo-box-item">` get applied for all comboboxes (also the default vaadin boxes).

Somehow they are part of the `#shadow` style afterwards.

The result is as follows:
![image](https://user-images.githubusercontent.com/14292982/53942128-3f345600-40ba-11e9-848d-e0ff328bc97d.png)

As you can see the `::before` element for the checkmark is missing and the padding looks horrible now.

Steps to reproduce:
1. Create a new Vaadin 13.0.0 Project
2. Create a view:
```
@Route
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
public class MainView extends VerticalLayout {

  public MainView() {
    ComboBox<String> comboBox = new ComboBox<>("Items", "Item 1", "Item 2", "Item 3");
    add(comboBox);
  }
}
```
3. Add the dependency in the `pom.xml`:
```
<dependency>
    <groupId>org.vaadin.gatanaso</groupId>
    <artifactId>multiselect-combo-box-flow</artifactId>
    <version>0.0.2</version>
</dependency>
```
4. Compile using the `production-mode` maven profile
5. Start the application providing the VM option `-Dvaadin.productionMode=true`

I am just not sure if thi is a problem of the vaadin production mode compilation process or if the addon is missing something in the implementation?

**Comment by gatanaso** [comment]
Thank you @Juchar for reporting this issue. I have identified and fixed the cause of the problem and will be releasing new versions soon. 

BR,
Goran
