### ISSUE TITLE
CustomElementRegistry issue with latest Vaadin components

### ISSUE THREAD

**Issue by jonmann20** [gatanaso/multiselect-combo-box#101]
Hello and thanks for the great component.  I'm having an issue when using this alongside the latest Vaadin components.

```
version.js:7 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
    at https://api.local.endpointhealth.dev:2081/__wds-outside-root__/1/node_modules/multiselect-combo-box/node_modules/@vaadin/vaadin-lumo-styles/version.js:7:16
```

**Comment by gatanaso** [comment]
Hi, with the merge of https://github.com/gatanaso/multiselect-combo-box/pull/106 and , the web component should now be compatible with the latest version of Vaadin (pending the update of the Flow counter part).
