### ISSUE TITLE
Tabbing into the multiselect-combo-box focuses the label

### ISSUE THREAD

**Issue by Lacuno** [gatanaso/multiselect-combo-box#103]
Hey guys!

I am currently using the multiselect-combo-box and when tabbing into the component the label will be selected with the first tab and another tab is needed to tab into the input field itself.
Is there a possibility to skip tabbing to the label?

Thanks!

**Comment by gatanaso** [comment]
Hi @Lacuno, I believe this is fixed with the latest version. I will close this issue for now, but please let me know if it still happens.
