### ISSUE TITLE
preselection of Values by Typing shows wrong values

### ISSUE THREAD

**Issue by JoergOstertag** [gatanaso/multiselect-combo-box#12]
If you start typing in an item the selection will be reduced. This is good. But the selected values do not match the typed in letters.

**Comment by JoergOstertag** [comment]
![2019-03-14 08_25_16-multiselect-combo-box demo](https://user-images.githubusercontent.com/17024921/54338801-34863d80-4633-11e9-9c7c-1f1e24eb40aa.png)

**Comment by JoergOstertag** [comment]
Tested on https://multiselect-combo-box.firebaseapp.com/demo/

**Comment by gatanaso** [comment]
Hi @JoergOstertag,

Thanks for reporting this issue. I believe it might have been introduced with the latest updates I introduced for this component, as the preselection worked in earlier versions quite well.

BR,
Goran
