### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Avec112** [gatanaso/multiselect-combo-box#120]
Running 4.0.0-rc2 and Vaadin 23.1.6 there is a JS error in browser console. 
```
Uncaught TypeError: this.$.comboBox.$.dropdown._setOverlayWidth is not a function at eval (multiselect-combo-box.js?48c8:481)
```

Thing the same problem occurs with Vaadin 23.1.3 and maybe more versions aswell.

**Comment by hons82** [comment]
There is a Vaadin component in 23.2.0 called [MultiselectCombobox ](https://vaadin.com/docs/latest/components/multi-select-combo-box)which will probably be the next version of this component.

**Comment by Avec112** [comment]
Thanks and yes I know. I have already started to use the new Multi-select Combo Box from Vaadin. 
I will just recommend to close this bug.
