### ISSUE TITLE
Multiselect-Combobox do not work on IE 11

### ISSUE THREAD

**Issue by domiq44** [gatanaso/multiselect-combo-box#27]
Hello,

Great work !
I have to use such a component both with Chrome and IE.
When I play with [demo](https://multiselect-combo-box.firebaseapp.com/demo/), I See that it does'nt work on it !
Is there any turn arround ?

Thanks.

Dominique

**Comment by gatanaso** [comment]
Hello Dominique,

Thank you for the feedback 🙏 

I suspect that the reason why the demo is not working in IE11 is that the online demo is not compiled to ES5, which is needed for IE11: https://polymer-library.polymer-project.org/2.0/docs/browsers

You could checkout the project and test it locally by running `polymer serve` (assuming you have the polymer cli installed) which should transpile it for you and serve the correct version when using IE11.

Hope this helps,

Goran

**Comment by gatanaso** [comment]
Reopening issue as the component demos and styling was broken in IE 11.
