### ISSUE TITLE
Enhancement: Allow combo-box renderer

### ISSUE THREAD

**Issue by moderndeveloperllc** [gatanaso/multiselect-combo-box#43]
First off, I love the component. It fills a real need in my app. The only additional thing I wish it did was to easily allow me to set the `renderer` on the `vaadin-combo-box-light element. My dropdown items have a couple of object properties concatenated.

**Comment by gatanaso** [comment]
Hi @moderndeveloperllc, thanks for the feedback and apologies for a bit late reply. One hacky way to override the current renderer would be:
```
multiselectComboBox.$.comboBox.renderer = function(root, owner, model) {
   // custom logic here
}
```
Though in this case one would also have to make sure to take care of the styling and the selected state for each item in the list.

**Comment by moderndeveloperllc** [comment]
@gatanaso Thanks. We still have a ways to go on our app, so I'll hold off on the implementation. I look forward to seeing what you can come up with.
