### ISSUE TITLE
Feature: allow custom values

### ISSUE THREAD

**Issue by cinquin** [gatanaso/multiselect-combo-box#5]
Great component.
It would be very useful to allow users to input custom values, as made possible by vaadin-combo-box.

**Comment by robertspizzarottisoft** [comment]
This would be useful, but it's also sometimes useful to restrict selection to items in the list so I'd ask that if this is implemented, there's an option to allow/dis-allow it.

**Comment by brendan-jefferis** [comment]
This would be useful, but it's also sometimes useful to restrict selection to items in the list so I'd ask that if this is implemented, there's an option to allow/dis-allow it.

**Comment by gatanaso** [comment]
implemented with #61
