### ISSUE TITLE
Is this component support with webpack?

### ISSUE THREAD

**Issue by fauzieuy** [gatanaso/multiselect-combo-box#54]
Hi, I'm working with rails and webpack 3.12.0 and have a problem with the following error

```
Uncaught TypeError: Class constructor  cannot be invoked without 'new'
    at HTMLElement.VaadinThemePropertyMixin (vaadin-theme-property-mixin.js:4)
    at HTMLElement.VaadinThemableMixin (vaadin-themable-mixin.js:8)
    at HTMLElement.VaadinThemePropertyMixin (vaadin-theme-property-mixin.js:4)
    at HTMLElement.VaadinTabIndexMixin (vaadin-control-state-mixin.js:11)
    at new VaadinControlStateMixin (vaadin-control-state-mixin.js:42)
    at new MultiselectComboBox (multiselect-combo-box.js:129)
    at HTMLElement._stampTemplate (template-stamp.js:451)
    at HTMLElement._stampTemplate (property-effects.js:2495)
    at HTMLElement.ready (element-mixin.js:647)
    at HTMLElement.ready (topic-form.js:227)
```

install via yarn (1.19.1)

--

I've try with webcompents latest (which is 2.4.0) and it's work well (pure html).

I have no idea why it's broken with rails & webpack.

**Comment by gatanaso** [comment]
Hi @fauzieuy 

Thank you for reporting this issue. I am not familiar with rails so I cannot say for sure what could be the issue. Regarding webpack, well the Vaadin platform uses it for the front-end stuff and in that context there haven't been any issues. Could you possibly share your config, it might help in resolving the issue?

**Comment by gatanaso** [comment]
For example, one thing regarding the `webcomponentsjs` is that you probably need to copy them as it's done in a typical Vaadin project (here is a snipped from the webpack config):
```
    new CopyWebpackPlugin([{
      from: `${baseDir}/node_modules/@webcomponents/webcomponentsjs`,
      to: `${build}/webcomponentsjs/`
    }]),
```

Hope this helps,
Goran

**Comment by fauzieuy** [comment]
Hi @gatanaso , thank you for the response.

I've push the sample app to this repo https://github.com/fauzieuy/sample_app.
Of course I've copy the `webcomponentsjs` from `node_modules` to the `javascripts/packs` as a typical Rails project using webpack (I'm using postinstall scripts on package to copy them). 

note : also I'm using `vaadin-combo-box` to see the config is working well
https://github.com/fauzieuy/sample_app/blob/master/app/javascript/packs/zi/multi-select.js

**Comment by gatanaso** [comment]
Thanks for sharing an example project. As I am not familiar with Rails myself, I did not run the project. But I wanted to know where are the sources for the `multiselect-combo-box`? 
I was able to quickly find the `@polymer` and `@vaadin` namespaces here: https://github.com/fauzieuy/sample_app/tree/master/app/javascript but not the ones for the `multiselect-combo-box`?

**Comment by fauzieuy** [comment]
@gatanaso sorry my mistake, I wasn't copied the `multiselect-combo-box` from `node_modules` to `packs`.
https://github.com/fauzieuy/sample_app/blob/9ccac64425547f8fc6db1a031cf3c4ad39e6beb3/post_install.sh#L23
And `multiselect-combox-box` is working well

Thank you for your time.

**Comment by gatanaso** [comment]
@fauzieuy np, was happy to help 👍
