### ISSUE TITLE
Match Lumo Styling

### ISSUE THREAD

**Issue by Juchar** [gatanaso/multiselect-combo-box#6]
The current implementation does not match the styling of the rest of the lumo components.
If using it in a form this is clearly a visual break.

It would be nice to have a theme that matches lumo (at least it should have the same style as the default combo box).

One example can be found here:
https://github.com/vaadin/vaadin-combo-box/issues/88#issuecomment-384958301

**Comment by gatanaso** [comment]
Hi @Juchar,

Thank you for the feedback and the suggestion. This is something that I have been considering and others have mentioned to me as well :)
I have already started to work on the theming support for this component and will be updating the styles to match the `lumo` theme as closely as possible.

BR,
Goran

**Comment by Juchar** [comment]
Thank you already, great work!

I have seen that you use the following code to generate a border:
```
border: 1px solid;
border-radius: calc(var(--lumo-border-radius) / 2);
border-color: var(--lumo-contrast-10pct);
```
Which produces the following result:
![image](https://user-images.githubusercontent.com/14292982/53620220-74d8cb00-3bf2-11e9-85f4-ec2c72af428d.png)

May I ask why not just using:
```
/* border: 1px solid; */
border-radius: var(--lumo-border-radius);
/* border-color: var(--lumo-contrast-10pct); */
```

which produces the following output:
![image](https://user-images.githubusercontent.com/14292982/53620209-69859f80-3bf2-11e9-9cd0-c31f7c4adf12.png)

This would better match the default style of ComboBox & TextField:

![image](https://user-images.githubusercontent.com/14292982/53620092-faa84680-3bf1-11e9-80a7-ef0beed80e14.png)
![image](https://user-images.githubusercontent.com/14292982/53620108-06940880-3bf2-11e9-8107-006fea132629.png)
---
Also I would slightly change the style of the tokens (completely subjective, personal opinion. I assume I can style it later on myself using a `theme-for` if you think it's a bad idea):

Now:
![image](https://user-images.githubusercontent.com/14292982/53620209-69859f80-3bf2-11e9-9cd0-c31f7c4adf12.png)

After:
![image](https://user-images.githubusercontent.com/14292982/53620481-68a13d80-3bf3-11e9-8f3a-c3ed80d6dc97.png)

Using:
```
[part="token"] {   
    background-color: var(--lumo-contrast-10pct);
    padding-left: calc(2*var(--lumo-space-xs));
}

[part="token-label"] {
    display: flex;
    align-items: center;
    font-size: var(--lumo-font-size-s);
    /* padding-right: var(--lumo-space-xs); */
}
```

What do you think about it?

**Comment by gatanaso** [comment]
Hi @Juchar ,

Thank you for the feedback and for the improvement ideas!
> ...
> Which produces the following result:
> ![image](https://user-images.githubusercontent.com/14292982/53620220-74d8cb00-3bf2-11e9-85f4-ec2c72af428d.png)
> ...
> which produces the following output:
> ![image](https://user-images.githubusercontent.com/14292982/53620209-69859f80-3bf2-11e9-9cd0-c31f7c4adf12.png)
> ...
> This would better match the default style of ComboBox & TextField:
> ...

Yes, those would be much better defaults and they align nicely with the existing components 👍 

> Also I would slightly change the style of the tokens (completely subjective, personal opinion. I assume I can style it later on myself using a `theme-for` if you think it's a bad idea):
> 
> Now:
> ![image](https://user-images.githubusercontent.com/14292982/53620209-69859f80-3bf2-11e9-9cd0-c31f7c4adf12.png)
> ...
> After:
> ![image](https://user-images.githubusercontent.com/14292982/53620699-304e2f00-3bf4-11e9-979b-e05f39c274f3.png)
> 
> What do you think about it?

I think that this is also a great improvement suggestion and it makes the tokens look much better 👍  

However I would continue to use a `background-color` value of `--lumo-contrast-20pct` as it's a very small difference, but it makes the token chips stand out just a bit more (completely subjective, personal opinion here as well :) ). 

Thank you again for providing these improvement ideas, I really appreciate it and will update the styles.

P.S. pull requests are always welcome! 🙏
