### ISSUE TITLE
Enhancement: Close combobox by clicking toggle button

### ISSUE THREAD

**Issue by naoak** [gatanaso/multiselect-combo-box#64]
Thanks for great library! 
We can close the combobox by clicking the outside of the combbox. In addition to this, I'd like to close it by clicking the toggle button when the combobox is opened.

**Comment by gatanaso** [comment]
Hey @naoak, just wanted to let you that this seems to be an issue with the underlying `vaadin-combo-box-light` element. I have investigated it, and opened an issue about it: https://github.com/vaadin/vaadin-combo-box/issues/869. Ideally it's best if it gets resolved as part of the `vaadin-combo-box`.

**Comment by naoak** [comment]
@gatanaso Sorry for the late response. Taking a look at the source codes around ComboBoxMixin, it certainly looks like that. Thank you for the clarification and letting me know!
