### ISSUE TITLE
Outdated Dependencies (alpha)

### ISSUE THREAD

**Issue by moderndeveloperllc** [gatanaso/multiselect-combo-box#66]
@gatanaso Just a heads up, Vaadin is in the process of updating lots of their components to the next point-release (mainly RTL styles I think). This includes `vaadin-combo-box` to 5.1.0 (alpha for  a few weeks), which conflicts with your `^5.0.9` in package.json. You may want to see if `^5.0` is sufficient as that will allow anything below a hypothetical version 6. This is an issue with web components in that I could be using your component on the same page as a newer version of `vaadin/vaadin-text-field`. The page will try to load both versions and fail of course.

FYI, here are the [latest (includes alpha) versions](https://github.com/vaadin/vaadin-core/blob/master/package.json). I just use `@vaadin/vaadin-core` in my projects, but that might be overkill for you.

Latest: 
```
"@vaadin/vaadin-combo-box": "^5.1.0-alpha1",
"@vaadin/vaadin-control-state-mixin": "^2.1.3",
"@vaadin/vaadin-lumo-styles": "^1.6.0",
"@vaadin/vaadin-material-styles": "^1.3.2",
"@vaadin/vaadin-text-field": "^2.6.0-alpha4",
"@vaadin/vaadin-themable-mixin": "^1.5.2",
```

**Comment by gatanaso** [comment]
@moderndeveloperllc Thanks for the heads up. Great idea to try and use `^5.0` as it might be just what's needed. I'll try to look into this and come back with some suggestions.

**Comment by moderndeveloperllc** [comment]
My bad. This wasn't a version issue in the traditional sense. A couple of the dependencies were in alpha, which weren't "stable" enough for your yarn to accept as valid per the package.json. So it pulled the last stable version which caused the conflict. Now that 5.1.0 is stable, there is no issue.

**Comment by gatanaso** [comment]
Ah yeah, you are right, I had totally forgotten about that "tiny" detail 😄 Glad the issue is resolved itself and things are working as you expected.
