### ISSUE TITLE
Readme invalid: bower command for Polymer 2 version installs Polymer 3

### ISSUE THREAD

**Issue by stefanuebe** [gatanaso/multiselect-combo-box#69]
When running `bower install --save gatanaso/multiselect-combo-box`, it will install as a result the ES6/polymer 3 based scripts. They do not contain html files and therefore cannot be used as stated in the readme.

Simplest solution is to download the polymer 2 branch and use the files locally (but not sure, how far they are still maintained or uptodate regarding issues).

**Comment by gatanaso** [comment]
Hi Stefan, thanks for opening this issue. 

What happens if you run `bower install --save gatanaso/multiselect-combo-box"#1.0.1"` ?

**Comment by stefanuebe** [comment]
Brings up the following dialog: 

```
Unable to find a suitable version for vaadin-combo-box, please choose one by typing one of the numbers below:
    1) vaadin-combo-box#^4.2.7 which resolved to 4.2.9 and is required by multiselect-combo-box#1.1.0
    2) vaadin-combo-box#^5.0.11 which resolved to 5.0.11 and is required by VAADIN

Prefix the choice with ! to persist it to bower.json
```

**Comment by stefanuebe** [comment]
Choosing one of them downloads the polymer 2 variant (html).

**Comment by gatanaso** [comment]
Thanks for verifying, that works as intended. I have added the version as part of the bower installation instructions now.

**Comment by stefanuebe** [comment]
Just as a side note, is 1.0.1 a typo? I used 1.1.0 :)
