### ISSUE TITLE
Change event is not fired when combo box is invalid.

### ISSUE THREAD

**Issue by stefanuebe** [gatanaso/multiselect-combo-box#70]
Currently there is a check inside `_handleItemRemoved` if the component is valid or not. If it is case 1, then a change event is fired; if case 2, then not - in both cases the `selectedItems` property is changed on client side. This leads to the problem, that server and client side state are not synchrone anymore, when my server side relies on the `change` event. 

I would expect the component to send the change event in every case, since the data has changed. Validation should happen of course, too, to update the visual state, but it should happen parallel to the event firing, so that the empty data is recognizable by listeners (in my case the server side).

(Found the issue in the Polymer 2 variant, but code constellation is the same in master).

A workaround could be listening to the event `selected-items-changed`, that is fired due to the `notifiy: true` setting, but then additional handling is needed, since that event is also fired initially.

**Comment by stefanuebe** [comment]
Same for the `_handleRemoveAllItems` method. Should be done parallel, not sequential.

Also the method `_comboBoxValueChanged` also has the same constellation, but here it might make sense to validate first before changing the `selectedItems` and prevent the change, if it is not valid (for instance to not have invalid items set into the client side state) - therefore to move the if(valid) up before the assignment.

**Comment by gatanaso** [comment]
Thanks @stefanuebe for raising this issue and for the provided details.

**Comment by gatanaso** [comment]
@stefanuebe I tried what you described here using V14 in npm mode (Polymer 3) and the value change event is always fired. Could you please provide a reproducible project I can have a look at, as well as the exact steps that lead to the described situation?

**Comment by stefanuebe** [comment]
Yes, I use the custom event `change`; not in CRUD but in an own server side implementation for V8 (using the V8 elements addon).

Which client side event would you instead propose to use in the P2 variant? `value-change` or `value-changed`.

**Comment by stefanuebe** [comment]
Tested it, both are not fired by the P2 variant, so I have to stick to the `change` event variant. 😬

**Comment by stefanuebe** [comment]
Side note: if it works for the P3 / latest version as intended, then please see this one as very low priority. As said, the 'change' event constellation is the same, so I simply thought, that others using the same approach will run into the same error. I for myself can simply fix it in the local files, since the elements addon doesn't use a dynamic bower update or similar but simple local available lib files, that can simply be modified / fixed.

**Comment by gatanaso** [comment]
> Yes, I use the custom event change; not in CRUD but in an own server side implementation for V8 (using the V8 elements addon).

Sounds interesting, is it something you plan to share?

> Tested it, both are not fired by the P2 variant, so I have to stick to the change event variant

Thanks for the info. The Polymer 2 variant is lower priority for now as even Vaadin is moving away from Polymer 2 and it has been deprecated in favour of LitElement.

>I for myself can simply fix it in the local files, since the elements addon doesn't use a dynamic bower update or similar but simple local available lib files, that can simply be modified / fixed

Great, thanks for letting me know. In that case I will close this issue and in case there are other issues later on we can revisit this.

BR,
Goran
