### ISSUE TITLE
Enhancement: Bubble filter attribute so _filterChanged runs

### ISSUE THREAD

**Issue by moderndeveloperllc** [gatanaso/multiselect-combo-box#73]
This should allow for custom filters as described here: https://cdn.vaadin.com/vaadin-combo-box/5.1.0/demo/#combo-box-filtering-demos. Currently that listener doesn't fire if placed on the main element.

Currently, I'm having to do something along the lines of:
```
multiselectElement.$.comboBox.addEventListener('filter-changed', (e) => {
      multiselectElement.$.comboBox.filteredItems = multiselectElement.items.filter(
          (item) => {
            const nameWithId = item['name'] + ' ' + item['id'];
            return nameWithId.toString().toLowerCase().indexOf(e.detail.value.toLowerCase()) > -1;
          });
    });
```
It works, but relies on going deep into the element, like it used to be with the renderer until you added that (works great BTW). Would be great to have that at the top level.

**Comment by gatanaso** [comment]
Thanks for letting me know @moderndeveloperllc. I will look into it.

**Comment by gatanaso** [comment]
Hi @moderndeveloperllc,

I finally found some time to work on this :) The api for adding a custom filter is now much cleaner (no need to access the underlying combo box). Your example would looks like this (note the `filter-value-changed` event):
```
multiselectElement.addEventListener('filter-value-changed', (e) => {
      multiselectElement.filteredItems = multiselectElement.items.filter(
          (item) => {
            const nameWithId = item['name'] + ' ' + item['id'];
            return nameWithId.toString().toLowerCase().indexOf(e.detail.value.toLowerCase()) > -1;
          });
    });
```
