### ISSUE TITLE
Installing via NPM results in "Failed to execute 'define' on 'CustomElementRegistry'"

### ISSUE THREAD

**Issue by Canuckaholic** [gatanaso/multiselect-combo-box#92]
I have installed this via npm and notice that it adds a `node_modules` folder inside the `multiselect-combo-box` folder with both `@vaadin` and `lit-element` modules.

When I attempt to run my application now I get a couple of error similar to:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
    at Object.parcelRequire.../../../../node_modules/multiselect-combo-box/node_modules/@vaadin/vaadin-text-field/node_modules/@vaadin/vaadin-lumo-styles/version.js
```

Any ideas?

**Comment by gatanaso** [comment]
HI @Canuckaholic 

I have been quite swamped with work and not much time lately to reply promptly here :) 

Are you using the component in a Vaadin project, if so, which version of Vaadin are you using? I haven't checked the compatibility with the newer versions, so there might be some issues arising from that as well.

**Comment by Canuckaholic** [comment]
Hello,

I actually figured it out that I was using a version of Vaadin components that was too old. Updating them fixed the problem.
