### ISSUE TITLE
token-misalignment after first row

### ISSUE THREAD

**Issue by berndhopp** [gatanaso/multiselect-combo-box#95]
tokens in the second, third row asf lack padding or margin to the left which the first row has

![grafik](https://user-images.githubusercontent.com/1919315/113304986-dd7b6000-9302-11eb-94d3-b1b7b02d7e77.png)

**Comment by gatanaso** [comment]
Hi, I think this should be fixed now with the latest release. You can check the demo for more details: https://multiselect-combo-box.web.app/
