### ISSUE TITLE
Conflict with vaadin-text-field

### ISSUE THREAD

**Issue by nc142j** [gatanaso/multiselect-combo-box#96]
See the following Console Error:
```
vaadin-text-field.js:148 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
    at http://neo.ds.dtveng.net:8003/node_modules/@vaadin/vaadin-grid/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js:148:16
```
When importing multiselect-combo-box. v2.4.2

It was suggested from other devs to try contacting you about updating the component with the latest vaadin components in the package.json

Note: I already tried removing the @vaadin/vaadin-test-field from nodules_modules and removing the package-lock.json and reinstall using npm install. 
I also tried running npm deduse no luck on either. 
Oh ya, and last thing is I must use the regular versions, not the alphas or betas, but regardless, those latest 2.5.0-* gave me the same error.

**Comment by nc142j** [comment]
Forgot to note I am using polymer 3

**Comment by FlorianWoelki** [comment]
I had this issue as well on a micro frontend architecture.

Right now, I've solved this issue by redefining the `customElements` function and checking if the element is already registered.

```js
const _customElementsDefine = window.customElements.define;
window.customElements.define = (name, cl, conf) => {
  if (!customElements.get(name)) {
    _customElementsDefine.call(window.customElements, name, cl, conf);
  }
};
```

**Comment by nc142j** [comment]
Thanks @FlorianWoelki, 

My custom element looks somewhat like code below. Where should that code be applied?

`import { html, css, LitElement } from "lit-element";
import { SharedStyles } from "../../shared-styles.js";
import "@polymer/paper-icon-button/paper-icon-button.js";
import "@vaadin/vaadin-form-layout/vaadin-form-layout.js";
import "@vaadin/vaadin-text-field/vaadin-text-field.js";
import "multiselect-combo-box/multiselect-combo-box.js";
import "@vaadin/vaadin-date-time-picker/vaadin-date-time-picker.js";
import {
  createSubcriptionItems,
  createTvodItems,
  createPackageItems,
} from "../../helpers/formCreator.js";

class PolicyDetailsContent extends LitElement {
  static get is() {
    return `policy-details-content`;
  }
  static get properties() {
    return {
      policyObj: {
        type: Object,
      },
      schemaObj: {
        type: Object,
      },
    };
  }
  static get styles() {
    return [SharedStyles, css``];
  }
  render() {
    return html`
      <style include="shared-styles dfw-styles dfw-custom-icons">
        /* css styles **/
      </style>
      /* Bunch of others html **/
    `;
  }

  constructor() {
    super();
  }

/* Bunch of JS Functions **/
  connectedCallback() {
    super.connectedCallback();
  }
}
window.customElements.define(PolicyDetailsContent.is, PolicyDetailsContent);
`

**Comment by FlorianWoelki** [comment]
This will be a global definition, so you need to make sure that this script is executed before any of your components load. In my case it is simply in the `index.html` file in a script tag.
