### ISSUE TITLE
How to use without a bundler

### ISSUE THREAD

**Issue by oskarrough** [gatanaso/multiselect-combo-box#98]
Hello, what dependencies to you need exactly to get this working on an otherwise empty html page? Or maybe I messed up the imports somehow. Appreciate any pointers because this combo box is really well done.

I've attempted here https://codepen.io/0skar/pen/dyNQzKW?editors=1010.

**Comment by gatanaso** [comment]
Hi, unfortunately you may need to use some sort of a bundler to produce your final output.
