### ISSUE TITLE
Close dropdown when toggle button clicked

### ISSUE THREAD

**Issue by roman-hak** [gatanaso/multiselect-combo-box#99]
If a combo box is in an opened state (i.e. a dropdown is opened) clicking on a toggle button should turn the combo box back to a closed stated (i.e. close the dropdown).

The original Vaadin combo box behaves like that so I think the multiselect combo box should follow this behavior.

**Comment by gatanaso** [comment]
Hi and thanks for reporting this issue. Unfortunately,  it looks like the underlying issue has not yet been fixed, as this has already been reported: https://github.com/gatanaso/multiselect-combo-box/issues/64.

I will close this as a duplicate.

**Comment by roman-hak** [comment]
Thanks for information and sorry for creating a duplicity. Next time I should definitely check already closed issues...
